version: XTARK-Mecanum

#Serial port param
port_name: /dev/ttyAMA0  #设备端口
baud_rate: 115200       #通信波特率，固定115200

#odom_frame: odom_raw       #里程计坐标系
base_frame: base_footprint  #底盘坐标系
#publish_odom_transform: False #是否发布odom->base_footprint坐标变换

#Mecanum params
encoder_resolution: 1440  #编码器分辨率
wheel_diameter: 0.097     #轮胎直径
wheel_a_mec: 0.095        #麦克纳姆运动模型A参数    
wheel_b_mec: 0.075        #麦克纳姆运动模型B参数
linear_correction_factor: 1.000    #线速度校准系数
angular_correction_factor: 1.000  #角速度校准系数

#Motor PID params
pid_rate:  25           #OpenCRP PID控制频率  
Kp: 300                 #OpenCRP电机控制PID，P参数
Ki: 0                   #OpenCRP电机控制PID，I参数
Kd: 200                 #OpenCRP电机控制PID, D参数

#Other
control_rate: 25        #底盘控制频率
